import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { JsonLd, PageShell, africaKeywords, siteUrl } from '@/components/site';
import { MerchantLogo, ProductCard, DestinationBar } from '@/components/shopping';
import { AddToListButton, SaveButton } from '@/components/marketplace-actions';
import { getCatalogProduct, getCatalogProducts } from '@/server/catalog';

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
 const {slug}=await params; const p=await getCatalogProduct(slug,'NG'); if(!p)return{title:'Product not found'};
 return {title:p.name,description:`Compare ${p.name} prices and merchant offers on TAMP Marketplace for shoppers across Africa.`,keywords:[...africaKeywords,p.name,p.brand,p.category,'price comparison'],alternates:{canonical:`/products/${slug}`},openGraph:{title:`${p.name} | TAMP Marketplace`,description:`Compare ${p.name} offers across participating merchants.`,url:`${siteUrl}/products/${slug}`,images:['/og-image.png']}};
}

export default async function Product({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{country?:string}>}){
 const {slug}=await params; const country=((await searchParams).country||'NG').toUpperCase(); const p=await getCatalogProduct(slug,country); if(!p)notFound();
 const related=(await getCatalogProducts({country,category:p.category.replaceAll(' ','-'),brand:p.brand,limit:8})).filter(x=>x.slug!==p.slug).slice(0,4);
 const primary=p.offers?.find(o=>o.affiliateId);
 return <PageShell active="products"><article className="market-page product-detail"><div className="crumbs">Home / Products / {p.category} / {p.name}</div><DestinationBar countryCode={country} compact/>
 <div className="product-detail-grid"><div className="detail-image"><span className="detail-icon">{p.icon}</span><span className="detail-discount">-{p.discount||0}%</span></div><div className="detail-copy"><div className="eyebrow">{p.brand.toUpperCase()} · {p.category.toUpperCase()}</div><h1>{p.name}</h1><div className="stars big">★★★★★ <em>{p.rating || '—'} · {p.reviews?.toLocaleString() || '—'} reviews</em></div><p className="lead">{p.description}</p><div className="detail-price"><strong>{p.price.toLocaleString()} {p.offers?.[0]?.currency || 'USD'}</strong>{p.oldPrice&&<del>{p.oldPrice.toLocaleString()} {p.offers?.[0]?.currency || 'USD'}</del>}<span>{p.discount ? `Save ${p.discount}%` : ''}</span></div><div className="detail-actions">{primary?.affiliateId?<a className="yellow-btn primary-btn" href={`/api/go/${primary.affiliateId}`}>Visit merchant →</a>:<a className="yellow-btn primary-btn" href={`/merchants/${p.merchant.toLowerCase()}?country=${country}`}>Visit merchant →</a>}<a className="outline-btn" href={`/products?country=${country}`}>＋ Compare</a><SaveButton item={{slug:p.slug,name:p.name,merchant:p.merchant,price:p.price,icon:p.icon}} /><AddToListButton item={{slug:p.slug,name:p.name,merchant:p.merchant,price:p.price,icon:p.icon}} /></div><p className="affiliate-small">The merchant handles checkout, payment, delivery and returns.</p></div></div>
 <section className="source-panel"><div><span className="source-kicker">KNOW THE SOURCE</span><h2>Where this product comes from</h2><p>TAMP is the discovery layer. The merchant named below is the store you visit for this offer. TAMP does not take payment or fulfill the order.</p></div><div className="source-facts"><div><small>Merchant source</small><b>{p.merchant}</b></div><div><small>Shopping destination</small><b>{country}</b></div><div><small>Checkout</small><b>With merchant</b></div></div></section>
 <section className="offer-section"><div className="section-heading"><h2>Compare merchant offers</h2><span>Final prices confirmed on merchant site</span></div><div className="offer-table">{(p.offers||[]).map((o,i)=><div className="offer-row" key={o.merchant}><MerchantLogo merchant={o.merchant}/><div><b>{o.merchant}</b><small>{i===0?'Featured offer':'Participating merchant'}</small></div><strong>{o.price.toLocaleString()} {o.currency}</strong><span>{o.status==='available'?'Destination available':o.status==='product-dependent'?'Product-dependent':'Verify at merchant'}</span>{o.affiliateId?<a className="yellow-btn" href={`/api/go/${o.affiliateId}`}>Visit merchant</a>:<a className="yellow-btn" href={`/merchants/${o.merchant.toLowerCase()}?country=${country}`}>View merchant</a>}</div>)}</div></section>
 <section className="info-grid"><div className="seo-card"><h2>About this product</h2><p>{p.description} Always verify specifications, warranty, delivery, taxes and return conditions on the merchant website before purchasing.</p></div><div className="seo-card"><h2>Before you buy</h2><p>Prices and availability can change. Merchant shipping coverage varies by country and address, especially across African markets.</p></div></section>{related.length>0&&<section className="related"><div className="section-heading"><h2>Related products</h2><a href="/products">View all →</a></div><div className="product-grid">{related.map(x=><ProductCard key={x.slug} product={x} countryCode={country}/>)}</div></section>}</article><JsonLd data={{'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description,brand:{'@type':'Brand',name:p.brand},offers:{'@type':'AggregateOffer',lowPrice:p.price,priceCurrency:p.offers?.[0]?.currency||'USD',offerCount:p.offers?.length||1,url:`${siteUrl}/products/${p.slug}`}}}/></PageShell>
}
