import { NextResponse } from 'next/server';
import { createPasswordResetToken, hashToken, PASSWORD_RESET_MINUTES } from '@/lib/auth';
import { query } from '@/lib/db';
import { sendPasswordResetEmail } from '@/lib/password-reset-email';
import { ensureAuthSchema } from '@/lib/auth-schema';
import { rateLimit, clientIp } from '@/server/security-rate-limit';
const GENERIC = { ok: true, message: 'If an account exists for that email, a password reset link has been sent.' };
const DELIVERY_ERROR = { ok: false, error: 'Password reset email is not configured yet. Please try again later.' };
export async function POST(request: Request) { const rl=await rateLimit(`auth-forgot:${clientIp(request)}`,5,60); if(!rl.allowed)return NextResponse.json({ok:false,error:'Too many password reset requests. Please try again shortly.'},{status:429,headers:{'Retry-After':'60'}}); try { await ensureAuthSchema(); if(!process.env.RESEND_API_KEY || !process.env.RESEND_FROM_EMAIL) return NextResponse.json(DELIVERY_ERROR,{status:503}); const body=await request.json().catch(()=>({})); const email=String(body.email||'').trim().toLowerCase(); if(!email||!email.includes('@')||email.length>254)return NextResponse.json(GENERIC); const result=await query<{id:string;email:string;name:string;password_hash:string|null}>('SELECT id,email,name,password_hash FROM users WHERE lower(email)=lower($1) AND active=true LIMIT 1',[email]); const user=result.rows[0]; if(!user?.password_hash)return NextResponse.json(GENERIC); await query('DELETE FROM password_reset_tokens WHERE user_id=$1 OR expires_at < NOW()',[user.id]); const token=createPasswordResetToken(); const tokenHash=hashToken(token); const expires=new Date(Date.now()+PASSWORD_RESET_MINUTES*60_000); await query('INSERT INTO password_reset_tokens (user_id,token_hash,expires_at) VALUES ($1,$2,$3)',[user.id,tokenHash,expires]); try { await sendPasswordResetEmail({to:user.email,name:user.name,token}); } catch(error) { await query('DELETE FROM password_reset_tokens WHERE token_hash=$1',[tokenHash]); console.error('Password reset email delivery failed',error); return NextResponse.json({ok:false,error:'Password reset email could not be sent right now. Please try again later.'},{status:503}); } return NextResponse.json(GENERIC); } catch(error) { console.error('Forgot password failed',error); return NextResponse.json({ok:false,error:'Password reset could not be started. Please try again later.'},{status:500}); } }
