'use client';
import {useEffect,useState} from 'react';
type Data={countries:any[];merchants:any[];categories:any[];products:any[]};
const empty:Data={countries:[],merchants:[],categories:[],products:[]};
export default function AdminPage(){const[data,setData]=useState(empty);const[analytics,setAnalytics]=useState<any>(null);const[users,setUsers]=useState<any[]>([]);const[deals,setDeals]=useState<any[]>([]);const[content,setContent]=useState<any[]>([]);const[error,setError]=useState('');const[saved,setSaved]=useState('');
 const load=async()=>{try{const rs=await Promise.all(['/api/admin','/api/admin/analytics','/api/admin/users','/api/admin/deals','/api/admin/content'].map(x=>fetch(x,{cache:'no-store'})));const ds=await Promise.all(rs.map(r=>r.json()));if(rs.some(r=>!r.ok)){setError(ds.find(d=>d.error)?.error||'Unable to load admin data.');return;}setData(ds[0]);setAnalytics(ds[1]);setUsers(ds[2].users);setDeals(ds[3].deals);setContent(ds[4].content);}catch{setError('Unable to load admin data.');}};
 useEffect(()=>{load()},[]);const save=async(path:string,body:any)=>{setError('');setSaved('');const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setError(d.error||'Save failed.');return;}setSaved('Saved.');load()};
 return <main style={{maxWidth:1250,margin:'40px auto',padding:'0 20px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:20,marginBottom:28}}><div><span className="eyebrow">TAMP MARKETPLACE</span><h1>Admin & Business Operations</h1><p>Manage the marketplace, content, users, deals and affiliate performance.</p></div><a className="outline-btn" href="/">Back to marketplace</a></div>{error&&<div className="error-box">{error}</div>}{saved&&<div className="success-box">{saved}</div>}
 <section className="admin-grid"><Stat title="Affiliate clicks" value={analytics?.summary?.clicks??'—'}/><Stat title="Conversions" value={analytics?.summary?.conversions??'—'}/><Stat title="Approved commission" value={analytics?.summary?.commission??'—'}/><Stat title="Approved order value" value={analytics?.summary?.order_value??'—'}/></section>
 <section className="admin-grid"><AdminForm title="Category" fields={['slug','name','icon']} labels={['Slug','Name','Icon']} onSave={v=>save('/api/admin/categories',v)}/><AdminForm title="Country" fields={['code','name','currency_code','default_language']} labels={['ISO code','Name','Currency','Language']} onSave={v=>save('/api/admin/countries',v)}/><AdminForm title="Merchant" fields={['slug','name','website_url','affiliate_network']} labels={['Slug','Name','Website URL','Affiliate network']} onSave={v=>save('/api/admin/merchants',v)}/><AdminForm title="Product" fields={['slug','title','brand','category_slug','image_url','description']} labels={['Slug','Title','Brand','Category slug','Image URL','Description']} onSave={v=>save('/api/admin/products',v)}/></section>
 <section className="admin-grid"><AdminForm title="Deal" fields={['merchant_product_id','country_code','title','discount_percent','ends_at']} labels={['Merchant product ID','Country','Title','Discount %','Ends at']} onSave={v=>save('/api/admin/deals',v)}/><AdminForm title="Content" fields={['slug','content_type','title','excerpt','body','status']} labels={['Slug','Type','Title','Excerpt','Body','Status']} onSave={v=>save('/api/admin/content',v)}/></section>
 <section className="admin-table"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><h2>Users</h2><a className="outline-btn" href="/api/admin/users/export">Export names & emails</a></div><table><thead><tr>{['Name / email','Country','Role','Provider','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}<small>{u.email}</small></td><td>{u.country_code||'Unknown'}</td><td>{u.role}</td><td>{u.provider}</td><td>{u.active?'Active':'Disabled'}</td></tr>)}</tbody></table></section>
 <Table title="Deals" heads={['Deal','Merchant','Product','Status']} rows={deals.map(d=>[d.title,d.merchant,d.product,d.active?'Active':'Inactive'])}/>
 <Table title="Content" heads={['Title','Type','Status','Updated']} rows={content.map(c=>[c.title,c.content_type,c.status,new Date(c.updated_at).toLocaleDateString()])}/>
 <Table title="Users by country" heads={['Country','Registered users']} rows={(analytics?.user_countries||[]).map((c:any)=>[c.country_code==='XX'?'Unknown':c.country_code,c.users])}/>
 <Table title="Merchant affiliate performance" heads={['Merchant','Clicks','Conversions','Commission']} rows={(analytics?.merchants||[]).map((m:any)=>[m.name,m.clicks,m.conversions,m.commission])}/>
 <Table title="Current catalog" heads={['Product','Category','Brand','Status']} rows={data.products.map(p=>[<>{p.title}<small>{p.slug}</small></>,p.category_slug||'—',p.brand||'—',p.active?'Active':'Inactive'])}/>
 </main>}
function Stat({title,value}:{title:string,value:any}){return <div className="admin-card"><span className="eyebrow">{title}</span><h2>{value}</h2></div>}
function AdminForm({title,fields,labels,onSave}:{title:string;fields:string[];labels:string[];onSave:(v:any)=>void}){const[v,setV]=useState<any>({});return <form className="admin-card" onSubmit={e=>{e.preventDefault();onSave(v)}}><h2>{title}</h2>{fields.map((key,i)=><label key={key}>{labels[i]}<input value={v[key]||''} onChange={e=>setV({...v,[key]:e.target.value})}/></label>)}<button className="yellow-btn" type="submit">Save {title.toLowerCase()}</button></form>}
function Table({title,heads,rows}:{title:string;heads:string[];rows:any[][]}){return <section className="admin-table"><h2>{title}</h2><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></section>}
