'use client';
import { useEffect, useState } from 'react';

type Lang='en'|'fr'|'pt'|'ar'|'sw'|'zu';
const T:Record<Lang,Record<string,string>>={
 en:{crumb:'Home / Merchants',eyebrow:'PARTNER MARKETPLACES',title:'Compare offers from popular stores.',lead:'Discover qualifying offers from participating merchants, then continue to the merchant for checkout, payment, shipping and fulfillment.',compare:'Compare before clicking',compareText:'Review product price, availability and visible merchant information before choosing an offer.',checkout:'Checkout is external',checkoutText:'The merchant controls payment, shipping, returns, warranties and customer service after you leave TAMP Marketplace.',regional:'Regional availability',regionalText:'Availability and delivery options can differ by country, product and merchant.',offers:'Compare offers',merchant:'Merchant checkout',note:'Merchant availability, pricing, shipping, returns and customer-service terms are controlled by the merchant. TAMP Marketplace does not hold or fulfill goods.'},
 fr:{crumb:'Accueil / Marchands',eyebrow:'PLATEFORMES PARTENAIRES',title:'Comparez les offres des boutiques populaires.',lead:'Découvrez les offres éligibles des marchands participants, puis rendez-vous chez le marchand pour le paiement, la livraison et l’exécution de la commande.',compare:'Comparez avant de cliquer',compareText:'Consultez le prix, la disponibilité et les informations visibles sur le marchand avant de choisir une offre.',checkout:'Le paiement se fait chez le marchand',checkoutText:'Le marchand contrôle le paiement, la livraison, les retours, les garanties et le service client après votre départ de TAMP Marketplace.',regional:'Disponibilité régionale',regionalText:'La disponibilité et les options de livraison peuvent varier selon le pays, le produit et le marchand.',offers:'Comparer les offres',merchant:'Paiement chez le marchand',note:'La disponibilité, les prix, la livraison, les retours et le service client relèvent du marchand. TAMP Marketplace ne détient ni ne livre les produits.'},
 pt:{crumb:'Início / Lojas',eyebrow:'PLATAFORMAS PARCEIRAS',title:'Compare ofertas de lojas populares.',lead:'Descubra ofertas elegíveis de lojas participantes e, depois, siga para a loja para pagamento, entrega e processamento do pedido.',compare:'Compare antes de clicar',compareText:'Veja o preço, a disponibilidade e as informações visíveis da loja antes de escolher uma oferta.',checkout:'O pagamento é feito na loja',checkoutText:'A loja controla pagamento, entrega, devoluções, garantias e atendimento depois que você sai do TAMP Marketplace.',regional:'Disponibilidade regional',regionalText:'A disponibilidade e as opções de entrega podem variar conforme o país, o produto e a loja.',offers:'Comparar ofertas',merchant:'Checkout da loja',note:'A disponibilidade, os preços, a entrega, as devoluções e o atendimento são controlados pela loja. O TAMP Marketplace não mantém nem entrega produtos.'},
 ar:{crumb:'الرئيسية / التجار',eyebrow:'المنصات الشريكة',title:'قارن العروض من المتاجر الشهيرة.',lead:'اكتشف العروض المؤهلة من التجار المشاركين، ثم انتقل إلى التاجر لإتمام الدفع والشحن وتنفيذ الطلب.',compare:'قارن قبل الانتقال',compareText:'راجع السعر والتوفر ومعلومات التاجر الظاهرة قبل اختيار العرض.',checkout:'إتمام الدفع لدى التاجر',checkoutText:'يتولى التاجر الدفع والشحن والإرجاع والضمان وخدمة العملاء بعد مغادرة TAMP Marketplace.',regional:'التوفر حسب المنطقة',regionalText:'قد تختلف إمكانية التوفر وخيارات التوصيل حسب البلد والمنتج والتاجر.',offers:'مقارنة العروض',merchant:'الدفع لدى التاجر',note:'التوفر والأسعار والشحن والإرجاع وخدمة العملاء تخضع لشروط التاجر. TAMP Marketplace لا يحتفظ بالمنتجات ولا يشحنها.'},
 sw:{crumb:'Nyumbani / Wauzaji',eyebrow:'MASOKO YA WASHIRIKA',title:'Linganisha ofa kutoka maduka maarufu.',lead:'Gundua ofa zinazofaa kutoka kwa wauzaji wanaoshiriki, kisha nenda kwa muuzaji kwa malipo, usafirishaji na utekelezaji wa agizo.',compare:'Linganisha kabla ya kubofya',compareText:'Kagua bei, upatikanaji na taarifa zinazoonekana za muuzaji kabla ya kuchagua ofa.',checkout:'Malipo yanafanywa kwa muuzaji',checkoutText:'Muuzaji anasimamia malipo, usafirishaji, marejesho, dhamana na huduma kwa wateja baada ya kuondoka TAMP Marketplace.',regional:'Upatikanaji wa kikanda',regionalText:'Upatikanaji na chaguo za uwasilishaji zinaweza kutofautiana kulingana na nchi, bidhaa na muuzaji.',offers:'Linganisha ofa',merchant:'Malipo kwa muuzaji',note:'Upatikanaji, bei, usafirishaji, marejesho na huduma kwa wateja hudhibitiwa na muuzaji. TAMP Marketplace haihifadhi wala kusafirisha bidhaa.'},
 zu:{crumb:'Ikhaya / Abathengisi',eyebrow:'IZIMAKETHE EZIBAMBA IQHAZA',title:'Qhathanisa amadili avela ezitolo ezidumile.',lead:'Thola amadili afanelekile kubathengisi ababambe iqhaza, bese uya kumthengisi ukuze ukhokhe, uthole ukulethwa futhi uqedele i-oda.',compare:'Qhathanisa ngaphambi kokuchofoza',compareText:'Hlola intengo, ukutholakala kanye nolwazi lomthengisi olubonakalayo ngaphambi kokukhetha idili.',checkout:'Ukukhokha kwenziwa kumthengisi',checkoutText:'Umthengisi ulawula ukukhokha, ukulethwa, ukubuyiselwa, iziqinisekiso kanye nesevisi yamakhasimende ngemva kokushiya i-TAMP Marketplace.',regional:'Ukutholakala ngokwesifunda',regionalText:'Ukutholakala nezinketho zokulethwa kungahluka kuye ngezwe, umkhiqizo nomthengisi.',offers:'Qhathanisa amadili',merchant:'Ukukhokha kumthengisi',note:'Ukutholakala, amanani, ukulethwa, ukubuyiselwa kanye nesevisi yamakhasimende kulawulwa umthengisi. I-TAMP Marketplace ayigcini noma ithumele izimpahla.'}
};
const names:Record<string,string>={Amazon:'Amazon',JUMIA:'JUMIA',AliExpress:'AliExpress',eBay:'eBay',TEMU:'TEMU'};
const desc=(l:Lang,n:string)=>({en:`${n} offers`,fr:`Offres ${n}`,pt:`Ofertas ${n}`,ar:`عروض ${n}`,sw:`Ofa za ${n}`,zu:`Amadili e-${n}`}[l]);
export function MerchantLocalized({items}:{items:string[][]}){const [lang,setLang]=useState<Lang>('en');useEffect(()=>{const f=()=>{const x=localStorage.getItem('tamp-language')||'en';setLang((['en','fr','pt','ar','sw','zu'].includes(x)?x:'en') as Lang)};f();addEventListener('tamp-language-change',f);addEventListener('storage',f);return()=>{removeEventListener('tamp-language-change',f);removeEventListener('storage',f)}},[]);const t=T[lang];return <div dir={lang==='ar'?'rtl':'ltr'}><div className="crumbs">{t.crumb}</div><div className="eyebrow">{t.eyebrow}</div><h1>{t.title}</h1><p className="lead">{t.lead}</p><div className="seo-grid">{items.map(([logo,name])=><article className="seo-card" key={name}><div className="merchant-logo" style={{marginBottom:12}}>{logo}</div><h2>{names[name]||name}</h2><p>{desc(lang,name)}. {t.lead}</p><div className="pill-row"><span className="pill">{t.offers}</span><span className="pill">{t.merchant}</span></div></article>)}</div><div className="seo-grid"><article className="seo-card"><h2>{t.compare}</h2><p>{t.compareText}</p></article><article className="seo-card"><h2>{t.checkout}</h2><p>{t.checkoutText}</p></article><article className="seo-card"><h2>{t.regional}</h2><p>{t.regionalText}</p></article></div><div className="site-note">{t.note}</div></div>}
