import type { Product, AvailabilityStatus } from '@/data/marketplace';
import { AddToListButton, SaveButton } from './marketplace-actions';
import { getDbCategories, getDbMerchants, getDbCountries } from '@/server/marketplace-db';

const statusLabel=(s:AvailabilityStatus)=>({'available':'Available','limited':'Limited','product-dependent':'Product dependent','not-available':'Not available','unknown':'Check merchant'})[s]||'Check merchant';
export function MerchantLogo({merchant,type}:{merchant?:string;type?:string}){const label=merchant||type||'?'; return <span className={`merchant-logo ${type||''}`}>{type==='jumia'?'✦':type==='ali'?'AE':type==='temu'?'TEMU':type==='amazon'?'a':type==='ebay'?'e':label.slice(0,1).toUpperCase()}</span>}
export function ProductCard({product,countryCode='NG'}:{product:Product;countryCode?:string}){const status=(product.offers?.[0]?.status||'unknown') as AvailabilityStatus; return <article className="product-card"><div className="product-image"><span>{product.discount?<b className="discount">-{product.discount}%</b>:null}</span><i>{product.icon}</i><SaveButton item={{slug:product.slug,name:product.name,merchant:product.merchant,price:product.price,icon:product.icon}} /></div><div className="product-meta"><small>{product.category} · {product.brand}</small><h3><a href={`/products/${product.slug}`}>{product.name}</a></h3><div className="stars">★★★★★ <em>{product.rating?product.rating:'—'} {product.reviews?`(${product.reviews.toLocaleString()})`:''}</em></div><div className="product-price"><strong>{product.price.toLocaleString()} {product.offers?.[0]?.currency||'USD'}</strong>{product.oldPrice&&<del>{product.oldPrice.toLocaleString()} {product.offers?.[0]?.currency||'USD'}</del>}</div><div className="product-merchant"><MerchantLogo merchant={product.merchant}/><span><small>Merchant source</small>{product.merchant}</span><a href={`/products/${product.slug}?country=${countryCode}`}>Compare →</a></div><div className={`shipping-status status-${status}`}><span>●</span>{statusLabel(status)}</div><div className="product-card-actions"><AddToListButton item={{slug:product.slug,name:product.name,merchant:product.merchant,price:product.price,icon:product.icon}} /></div></div></article>}
export async function FilterPanel({countryCode='NG',activeCategory='',activeBrand='',activeMerchant=''}:{countryCode?:string;activeCategory?:string;activeBrand?:string;activeMerchant?:string}){const [categories,brands,merchants]=await Promise.all([getDbCategories(),(async()=>{const {query}=await import('@/lib/db');const r=await query<{brand:string}>(`SELECT DISTINCT brand FROM products WHERE active=TRUE AND brand IS NOT NULL AND trim(brand)<>'' ORDER BY brand LIMIT 24`);return r.rows.map(x=>x.brand);})(),getDbMerchants(countryCode)]);const link=(key:string,value:string)=>`/products?country=${countryCode}&${key}=${encodeURIComponent(value)}`;return <aside className="filter-panel"><div className="filter-title"><h2>Filter products</h2><a href="/products">Reset</a></div><details open><summary>Category</summary>{categories.map(x=><a className={activeCategory===x.slug?'filter-link active':''} href={link('category',x.name)} key={x.slug}><span className="fake-check">{activeCategory===x.slug?'✓':''}</span>{x.name}</a>)}</details><details open><summary>Price</summary><div className="price-fields"><input placeholder="Min"/><span>—</span><input placeholder="Max"/></div></details><details open><summary>Brand</summary>{brands.map(x=><a className={activeBrand===x.toLowerCase()?'filter-link active':''} href={link('brand',x)} key={x}><span className="fake-check">{activeBrand===x.toLowerCase()?'✓':''}</span>{x}</a>)}</details><details open><summary>Merchant</summary>{merchants.map(x=><a className={activeMerchant===x.name.toLowerCase()?'filter-link active':''} href={link('merchant',x.name)} key={x.slug}><span className="fake-check">{activeMerchant===x.name.toLowerCase()?'✓':''}</span>{x.name}</a>)}</details><details><summary>Rating</summary>{['4 stars & up','3 stars & up','2 stars & up'].map(x=><label key={x}><input type="radio" name="rating"/> {x}</label>)}</details></aside>}
export async function DestinationBar({countryCode='NG',compact=false}:{countryCode?:string;compact?:boolean}){const [countries,current]=await Promise.all([getDbCountries(),getDbCountries().then(list=>list.find(c=>c.code===countryCode.toUpperCase())||list[0])]);if(!current)return null;return <form className={`destination-bar ${compact?'compact':''}`} action="/products" method="get"><span className="destination-icon">🌍</span><div><b>Shop in {current.flag} {current.name}</b><small>Availability is checked by destination</small></div><select name="country" defaultValue={current.code} aria-label="Shopping destination">{countries.map(c=><option key={c.code} value={c.code}>{c.flag} {c.name}</option>)}</select><button type="submit">Update</button></form>}
